### ISSUE TITLE
Checklist items for Workshop 1: Part 1

### ISSUE THREAD

**Issue by mtaromi** [AdeptiC/Tower-Defence-Game#2]
Create a project hosted on GitHub with a markdown file
with a draft of a project plan.

Checklist:

- [x] Group of five students organized and recorded on Canvas.
- [x] Git: `name` and `email` set in `.gitconfig` properly for all 5 students.
- [x] Git: changes tracked through `git`.
- [x] `README.md` with a project description.
- [x] GitHub: project hosted on GitHub.
- [x] GitHub: GitHub repository shared with Masoumeh ([`mtaromi`]). 
- [x] GitHub: GitHub repository link sent to Masoumeh by email or Canvas.
- [x] `README.md` with a table/list of the 5 group members and their GitHub handles
- [x] `README.md`: Declaration section built with an associated commit from each of the students. (See below)
- [x] `README.md`: proper markdown with headings / etc. 
- [x] `README.md` with plan: What will you implement? How will it work? What kind of features will it have?
- [x] `README.md` with plan: which language(s) will you use?
- [x] `README.md` with plan: what build system will you use?
- [x] Git: at least one commit from each student in the group.
- [x] no force pushes to master/main (if you need to undo changes, use a new commit).

**Comment by mtaromi** [comment]
@AdeptiC, @Jakobloula, @Zeruxe, @Akbar-163, and @zakariyams 

I reviewed the checklist items for workshop 1: part 1 and and you seem to fulfill most of the items. Good job! 🎉
There are two minor items left to be done. Please check and complete them before the next workshop.
