### ISSUE TITLE
Checklist items for Workshop 2

### ISSUE THREAD

**Issue by mtaromi** [AdeptiC/Tower-Defence-Game#42]
Part 1 - OO Design 

- [x] Carry on with your implementation adding more features
- [x] Create few issues on using GRASP which are “closed” with an associated implementation

Part 2 - Using version control software (Git)

- [x] Add a .gitignore file to your project
- [x] Has a revert commit (don’t edit history: create a new revert commit!).
- [x] Has a branch implementing a small feature.
- [x] Has a merge commit (of the branch)
- [x] Has a branch in conflict with main/master 
- [x] Try to merge and resolve the merge conflict
- [x] Has working compilation and running instructions in the README.
- [x] Has issues associated with each of your changes.

**Comment by mtaromi** [comment]
Part 1 - OO Design: #37 #38 #41  

Part 2 Checklist: #9 

You seem to complete all the items. Good job! 🎉

I am closing this issue.
