### ISSUE TITLE
Workshop 3 - Checklist

### ISSUE THREAD

**Issue by Akbar-163** [AdeptiC/Tower-Defence-Game#43]
Part 1 (unit testing)

- [x]  Has a unit test.
- [x] Has several unit tests of different features and modules.
- [x] Tests are passing on master/main branch.
- [x] README with instructions of how to run the unit tests. 
- [x] README with instructions of how to generate code coverage information for your unit tests.
- [x] README with instructions of how to run a linter for your project.
- [x] If you are using assets found online as part of your project, please explicitly list  these on the README.

**Comment by mtaromi** [comment]
@Akbar-163, @zakariyams, @AdeptiC, @Jakobloula, and @Zeruxe 

Keep going!
Please complete the items by the next workshop on April 26. Also, mention the corresponding issue/commit for each item, so that I can follow up.
