### ISSUE TITLE
Workshop 3 - Checklist Part 2

### ISSUE THREAD

**Issue by Akbar-163** [AdeptiC/Tower-Defence-Game#44]
Part 2

- [x] CI(Continuous Integration) through Github Actions.
- [x] CI checks that your code compiles or parses.
- [x] CI checks that the unit tests are passing.
- [x] Master/Main is passing or is green.
- [x] CI "badge" on the README.
- [x] Optional items below
- CI produces code coverage info.
- CI performs lint checks.

**Comment by mtaromi** [comment]
@Akbar-163, @zakariyams, @AdeptiC, @Jakobloula, and @Zeruxe

Keep going!
Please complete the items by the next workshop on April 26. Also, mention the corresponding issue/commit for each item, so that I can follow up.

**Comment by mtaromi** [comment]
@Akbar-163, @zakariyams, @AdeptiC, @Jakobloula, and @Zeruxe

For the next workshops, please always mention the related commit/issues/PRs next to each item.
