### ISSUE TITLE
Checklist items for Workshop 4

### ISSUE THREAD

**Issue by mtaromi** [AdeptiC/Tower-Defence-Game#45]
Start using pull requests and doing code review in your project. Use this while you carry on with your project implementation.

Checklist:

- [x] Your project has pull requests and code review.
- [x] Each student has created at least one pull request.
- [x] Each student has performed at least one code review.
- [x] Each student has merged his own pull request after the code review.
- [x] `master`/`main` is passing / green. (and should be always from now on!)

**Comment by mtaromi** [comment]
@AdeptiC, @Jakobloula, @Zeruxe, @Akbar-163, and @zakariyams 

Please invite me to the project, so that I have the required access.

**Comment by Yoosseph** [comment]
> @AdeptiC, @Jakobloula, @Zeruxe, @Akbar-163, and @zakariyams
> 
> Please invite me to the project, so that I have the required access.

What kind of acess do you mean? Are you not already invited?

**Comment by mtaromi** [comment]
Please go to 'Setting->Collaborators (left side-bar)', and add me (mtaromi) there. 
Thank you.
