### ISSUE TITLE
Workshop 2 - Checklist

### ISSUE THREAD

**Issue by Yoosseph** [AdeptiC/Tower-Defence-Game#9]
Checklist:
 
- [x]    Add a .gitignore file to your project
- [x]    Has a revert commit (don’t edit history: create a new revert commit!).
- [x] #11
- [x] #12
- [x]    Has a branch in conflict with main/master 
- [x]    Try to merge and resolve the merge conflict
- [x]    Has working compilation and running instructions in the README.
- [x]    Has issues associated with each of your changes.

**Comment by Yoosseph** [comment]
This is a checklist for us just so we can keep track of what progress has been done.
